apiVersion: v1
kind: Service
metadata:
  name: feature-toggle
  namespace: confuse
  labels:
    app: feature-toggle
    service: features
spec:
  type: ClusterIP
  selector:
    app: feature-toggle
  ports:
  - name: http
    port: 3099
    targetPort: 3099
    protocol: TCP
